[DEFAULT]
importdir = import

[tkscan]
scanner = 
resolution = 600
file_format = tiff
destination = /home/sebastien/scans
prefix = scanned
batch_interval = 20
language = 
scan_area_enabled = false
scan_area_left = 0
scan_area_top = 0
scan_area_width = 148
scan_area_height = 105
crop_border = 100
jpeg_quality = 85
png_compress = 6
tiff_compression = deflate

